### ISSUE TITLE
Adapt different content type for the CAR format

### ISSUE THREAD

**Issue by Gozala** [web3-storage/ucanto#269]
As @gobengo pointed out there is a [application/vnd.ipld.car](https://www.iana.org/assignments/media-types/application/vnd.ipld.car) that is been used by IPFS gateways.

We should switch over to using that as content type.

**Comment by Gozala** [comment]
Note we should also figure out a way to do this without breaking existing clients that send requests and expect responses in `application/car` format.

**Comment by Gozala** [comment]
@gobengo on the related note we may also want to negotiate block encoding & hashing algorithm for the blocks inside the CARs. I was thinking using something like `application/car+cbor`, but sounds like that would not be a good idea. Do you know of a better way ?

**Comment by gobengo** [comment]
> I was thinking using something like application/car+cbor

I think that's about as good as it gets in media types. 'structured syntax suffix'
Helpful backstory here:
https://www.rfc-editor.org/rfc/rfc6838.html#section-4.2.8

> Do you know of a better way ?

Nope. It's line with things like [`application/ld+json`](https://www.iana.org/assignments/media-types/application/ld+json).
Or this with multiple (but afaict there are not great exemplars for composing many suffixes like this) [`application/credential+ld+json`](https://www.w3.org/TR/vc-data-model-2.0/#media-type)

**Comment by gobengo** [comment]
> I was thinking using something like application/car+cbor

Perhaps it should be `{otherMediaType}+car` e.g. `application/car+cbor` 🤔 ([via @jonnycrunch here sort of](https://github.com/ipfs/ipfs/issues/36#issuecomment-470617316))

**Comment by gobengo** [comment]
For our cases, `application/vnd.ipld.car.json` probably makes sense (when debugging an ipld.car response as car->dag-json)

**Comment by Gozala** [comment]
This got fixed
