### ISSUE TITLE
Compatibility with Zod

### ISSUE THREAD

**Issue by Gozala** [web3-storage/ucanto#40]
[Zod](https://zod.dev/) looks pretty neat and in many ways similar to how capabilities are defined in the library. It seems like a good idea to make it possible to use zod schemas in capability defs.

**Comment by hugomrdias** [comment]
also from the zod ecosystem, there's https://github.com/trpc/trpc which might be interesting to look at

**Comment by Gozala** [comment]
I have looked into integrating / supporting Zod into this library but have not yet figured how to address couple of issues:

1. We need to be able to define custom "decoders" (a.k.a validators in Zod). Specifically we need equivalent of [`Link` decoder](https://github.com/web3-storage/ucanto/blob/main/packages/validator/src/decoder/link.js) which I can't figure out how to make.

    I think `z.unknown().refine(...)` might work, yet it is still unclear to me how would we add additional methods.
2. We need to start supporting DAGs natively in capabilities (see #39) that is allow embedding blocks in the capabilities but turn those into links during encoding.

    It is going to be straight forward to iterate on this using built-in stuff like "decoders". With Zod I don't even know where I would start on this. 

3. I would prefer to avoid introducing tight dependency on Zod itself, it is third party library with goals that may or may not align in the future.

    I think it would be far more reasonable to introduce compatibility through [`safeParse`](https://zod.dev/?id=safeparse#safeparse) method which is just different flavor of our `decode` method. That way capability definitions would be able to accept zod validators without having to introduce tight coupling with zod library itself.

**Comment by Gozala** [comment]
I think it would be best to start with something as simple as `Zod` decoder which could take arbitrary zod validator and make it valid decoder e.g. `Zod.from(z.string())`. This would allow us to try using zod in our code base & if we find it to be successful we could remove need for `Zod.from` wrapper by updating our `Decoder` interface to be compatible with `Zod.safeParse`.

**Comment by Gozala** [comment]
I have also run into issues with loading zod from https://cdn.skypack.dev/zod or from any of the unpack urls https://unpkg.com/browse/zod@3.19.1/lib/

**Comment by hugomrdias** [comment]
agree let add optional support and not depend on it directly
