### ISSUE TITLE
Support `can: store/*` like patterns in validators

### ISSUE THREAD

**Issue by Gozala** [web3-storage/ucanto#87]
Right now validator would not allow you to derive `store/add` from `store/*` because it does not know `store/*` capability. We should implement support for such patterns in the ucanto so it's possible to delegate all current and future capabilities.

**Comment by Gozala** [comment]
Although it is not obvious that we could support `*` natively, because how would we validate if one `store/*` can be derived from another `store/*` without knowing how to compare `with` fields or other caveats. Which is to say it's probably best to make `store/*` explicit capability one can derive from, however there are few things that need careful consideration:

1. `store/*` capability definition should be aware of all the caveats otherwise some might get escalated down the line e.g.

     ```
     { can: "store/*", with: DID, size: 100 }
                     ^
                     |
     { can: "store/*", with: DID }
                     ^
                     |
     { store:"store/add", with:"did:key:zAlice", size:200 }
    ```

     In the chain above if `store/*` capability is defined as `capability({ can: "store/*", with: DID })` it would ignore imposed `size` caveat and allow `store/add` to escalate. 


Maybe we should have a special handling of `store/*` like capabilities disallowing any caveats preventing possibility of accidental escalation. Alternatively we could just extend validator in a way that would just parse `store/*` capabilities just as if they were capability been validated, that is `store/add` in this case. In this case we would just use same `StoreAdd` capability def and recognize all it's caveats.

**Comment by hugomrdias** [comment]
This is true for all wildcard caps like `voucher/*`, `account/*` etc the only way right now to make this work is to make a fake Server Provider for `account/*`

I would prefer explicit wildcard cap definition including all the caveats that need to be tested.
But not all caveats are created equal, things like voucher/redeem have `identity` caveat like `mailto:hugo@gmail.com` so voucher/* should have `mailto:*` in the definition so on and so on other things like more generic information about an invocation like metadata or references to other things dont need to bubble up to the wildcard definition but they MAY be validated by the invocation handler.

**Comment by Gozala** [comment]
> This is true for all wildcard caps like `voucher/*`, `account/*` etc the only way right now to make this work is to make a fake Server Provider for `account/*`

I'm not sure I understand this. Why do you need a fake provider ? E.g. here we define `can: *` capability

https://github.com/web3-storage/w3-protocol/blob/master/packages/access/src/capabilities/any.js

and then derive `store/*` capability from it

https://github.com/web3-storage/w3-protocol/blob/3b09d12ad1fe3d6ee7d2c86a0f7673e87349a8ae/packages/access/src/capabilities/store.js#L11-L18

These definitions also sort of imply that you can't add any caveats on `store/*` delegation.

**Comment by Gozala** [comment]
> I would prefer explicit wildcard cap definition including all the caveats that need to be tested.
> But not all caveats are created equal, things like voucher/redeem have `identity` caveat like `mailto:hugo@gmail.com` so voucher/* should have `mailto:*` in the definition so on and so on other things like more generic information about an invocation like metadata or references to other things dont need to bubble up to the wildcard definition but they MAY be validated by the invocation handler.

I'm not sure I understand what you mean here. I think you're saying that explicit definition of `vourcher/*` capability is a good idea.

Overall I'm not sure caveats in `ns/*` capability is a good idea at all. Because different derivatives may assign different meaning to the same caveat (although argument can be made that maybe they should not do that).

**Comment by Gozala** [comment]
All in all I feel like we should not rush implementing a native solution here. It's probably best to just wait and learn from experience and only after pursue removal of boilerplate

**Comment by hugomrdias** [comment]
last time i tried this even if the cap definition was done right .ie derive ns/something from ns/* ucanto still doesnt know about it you need to define a fake ns/* provider for the invocation to work.

Regarding the caveats i agree we should see what works best we a few implementations first
